name: Deploy my html to Heroku
on: [push]

jobs:
  heroku:
    runs-on: ubuntu-latest
    steps:
    - name: push to heroku
      env :
        HEROKU_REGISTRY_URL: registry.heroku.com
        HEROKU_TOKEN : ${{ secrets.HEROKU_API_KEY }}
      run : |
        echo $HEROKU_API_KEY | docker login --username=_ $HEROKU_REGISTRY_URL --password-stdin
        export HEROKU_API_KEY=$HEROKU_TOKEN
        heroku container:login
        heroku container:push web --app ${{ secrets.HEROKU_APP_NAME }}
        heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
        heroku ps:scale web=1 --app ${{ secrets.HEROKU_APP_NAME }}
